group: travis_latest
language: python
matrix:
  include:
    - name: "dist: trusty"
      dist: trusty
      python: 3.6
    - name: "dist: xenial"
      dist: xenial
      python: 3.6
    - name: "os: osx"
      language: generic  # 'language: python' is not yet supported
      os: osx
      # before_install: brew upgrade python
    - name: "os: windows"
      language: sh  # 'language: python' is not yet supported
      os: windows
      before_install:
        - choco install python --version 3.6.8
        # - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
      script: py ./platform_info.py

install: chmod +x platform_info.py
script: ./platform_info.py
