group: travis_latest
language: python
matrix:
  include:
    - name: "dist: trusty"
      dist: trusty
      python: 3.6
    - name: "dist: xenial"
      dist: xenial
      python: 3.6
    - name: "os: osx"
      language: generic  # 'language: python' is not yet supported
      os: osx
    - name: "os: windows"
      language: generic  # 'language: python' is not yet supported
      os: windows

install: true
script: python platform_info.py
