group: travis_latest
language: python
python: 3.6
matrix:
  include:
    - name: "dist: trusty"
      dist: trusty
    - name: "dist: xenial"
      dist: xenial
install: true
script: python platform_info.py
