group: travis_latest
language: python
python: 3.6
matrix:
  include:
    - name: "dist: trusty"
      dist: trusty
    - name: "dist: xenial"
      dist: xenial
    - name: "os: osx"
      python: true
      os: osx
    - name: "os: windows"
      language: c  # 'python' is not yet supported
      os: windows

install: true
script: python platform_info.py
